# Zeitgeist Subsquid Processor - Testnet Kubernetes Manifests
# Based on working mainnet deployment - STANDARDIZED RESOURCES
# Will replace testnet indexers on: 170.187.185.134 and 194.233.162.35
#
# Changes Made:
# 1. Fixed indexer command: yarn run indexer:up
# 2. Fixed API commands: yarn run api:start
# 3. Standardized ALL resources to match mainnet (prevents resource issues)
# 4. Added imagePullPolicy: Always for consistent deployments
# 5. Unified approach across both environments

---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: zeitgeist-processor-testnet
  labels:
    app: zeitgeist-processor-testnet

---
# ConfigMap for testnet environment variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: processor-config
  namespace: zeitgeist-processor-testnet
data:
  PROJECT_NAME: "zeitgeist-indexer"
  WS_NODE_URL: "wss://bsr.zeitgeist.pm"  # Testnet WebSocket
  DB_NAME: "postgres"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_HOST: "processor-postgres"
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  REDIS_HOST: "processor-redis"
  REDIS_PORT: "6379"
  ARCHIVE_GATEWAY_URL: "https://v2.archive.subsquid.io/network/zeitgeist-testnet"  # Testnet archive
  PROCESSOR_PROMETHEUS_PORT: "9090"
  BATCH_SIZE: "100"
  BLOCK_WINDOW: "100000"
  GRAPHQL_SERVER_PORT: "4000"
  GRAPHQL_SERVER_HOST: "localhost"
  WARTHOG_SUBSCRIPTIONS: "true"
  GQL_PORT: "4350"
  NODE_ENV: "test"  # Testnet environment

---
# Secret for testnet sensitive data
apiVersion: v1
kind: Secret
metadata:
  name: processor-secrets
  namespace: zeitgeist-processor-testnet
type: Opaque
stringData:
  DB_PASS: "postgres"
  POSTGRES_PASSWORD: "postgres"
  REDIS_PASS: "redis"

---
# PostgreSQL StatefulSet - STANDARDIZED to match mainnet resources
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: processor-postgres
  namespace: zeitgeist-processor-testnet
spec:
  serviceName: processor-postgres
  replicas: 1
  selector:
    matchLabels:
      app: processor-postgres
  template:
    metadata:
      labels:
        app: processor-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: processor-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: processor-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: processor-secrets
              key: POSTGRES_PASSWORD
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"  
          limits:
            memory: "4Gi"
            cpu: "2000m"  
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 30
          periodSeconds: 10
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 20Gi  # Keep smaller storage for testnet (cost optimization)
      storageClassName: linode-block-storage-retain

---
# PostgreSQL Service
apiVersion: v1
kind: Service
metadata:
  name: processor-postgres
  namespace: zeitgeist-processor-testnet
spec:
  selector:
    app: processor-postgres
  ports:
  - port: 5432
    targetPort: 5432
  clusterIP: None

---
# Redis StatefulSet - STANDARDIZED to match mainnet resources
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: processor-redis
  namespace: zeitgeist-processor-testnet
spec:
  serviceName: processor-redis
  replicas: 1
  selector:
    matchLabels:
      app: processor-redis
  template:
    metadata:
      labels:
        app: processor-redis
    spec:
      containers:
      - name: redis
        image: redis:6.0-alpine
        ports:
        - containerPort: 6379
        env:
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              name: processor-secrets
              key: REDIS_PASS
        command:
        - sh
        - -c
        - "redis-server --appendonly yes --requirepass ${REDIS_PASS}"
        volumeMounts:
        - name: redis-storage
          mountPath: /data
        resources:
          requests:
            memory: "256Mi"  # STANDARDIZED: Same as mainnet
            cpu: "100m"     # STANDARDIZED: Same as mainnet
          limits:
            memory: "512Mi"  # STANDARDIZED: Same as mainnet
            cpu: "250m"     # STANDARDIZED: Same as mainnet
        readinessProbe:
          exec:
            command:
            - redis-cli
            - -a
            - $(REDIS_PASS)
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - redis-cli
            - -a
            - $(REDIS_PASS)
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
  volumeClaimTemplates:
  - metadata:
      name: redis-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi  # Keep smaller storage for testnet (cost optimization)
      storageClassName: linode-block-storage-retain

---
# Redis Service
apiVersion: v1
kind: Service
metadata:
  name: processor-redis
  namespace: zeitgeist-processor-testnet
spec:
  selector:
    app: processor-redis
  ports:
  - port: 6379
    targetPort: 6379
  clusterIP: None

---
# Indexer Deployment - STANDARDIZED resources
apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor-indexer
  namespace: zeitgeist-processor-testnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor-indexer
  template:
    metadata:
      labels:
        app: processor-indexer
    spec:
      containers:
      - name: indexer
        image: zeitgeistpm/squid-processor:unified
        command: ["yarn", "run", "indexer:up"]
        imagePullPolicy: Always  # Ensures latest image is pulled
        envFrom:
        - configMapRef:
            name: processor-config
        - secretRef:
            name: processor-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m" 
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "ps aux | grep -v grep | grep node"
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "ps aux | grep -v grep | grep node"
          initialDelaySeconds: 30
          periodSeconds: 10

---
# API Deployment (GraphQL Server) - STANDARDIZED resources
apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor-api
  namespace: zeitgeist-processor-testnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor-api
  template:
    metadata:
      labels:
        app: processor-api
    spec:
      containers:
      - name: api-test
        image: zeitgeistpm/squid-processor:unified
        command: ["yarn", "run", "api:start"]
        imagePullPolicy: Always  # Ensures latest image is pulled
        ports:
        - containerPort: 4350
          name: graphql-test
        env:
        - name: GQL_PORT
          value: "4350"
        envFrom:
        - configMapRef:
            name: processor-config
        - secretRef:
            name: processor-secrets
        resources:
          requests:
            memory: "512Mi"  # STANDARDIZED: Same as mainnet api-main
            cpu: "250m"     # STANDARDIZED: Same as mainnet api-main
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /graphql
            port: 4350
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /graphql
            port: 4350
          initialDelaySeconds: 60
          periodSeconds: 30
      - name: api-subscriptions
        image: zeitgeistpm/squid-processor:unified
        command: ["yarn", "run", "api:start"]
        imagePullPolicy: Always  # Ensures latest image is pulled
        ports:
        - containerPort: 4000
          name: graphql-subs
        env:
        - name: GQL_PORT
          value: "4000"
        envFrom:
        - configMapRef:
            name: processor-config
        - secretRef:
            name: processor-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /graphql
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /graphql
            port: 4000
          initialDelaySeconds: 60
          periodSeconds: 30

---
# API Service - LoadBalancer for Direct External Access
apiVersion: v1
kind: Service
metadata:
  name: processor-api
  namespace: zeitgeist-processor-testnet
spec:
  type: LoadBalancer
  selector:
    app: processor-api
  ports:
  - name: graphql-test
    port: 4350
    targetPort: 4350
  - name: graphql-subs
    port: 4000
    targetPort: 4000
  - name: metrics
    port: 9090
    targetPort: 9090

---
# HorizontalPodAutoscaler for API - STANDARDIZED to match mainnet
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: processor-api-hpa
  namespace: zeitgeist-processor-testnet
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: processor-api
  minReplicas: 1
  maxReplicas: 3  # STANDARDIZED: Same as mainnet
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

---
# NetworkPolicy for testnet - STANDARDIZED to match mainnet
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: processor-network-policy
  namespace: zeitgeist-processor-testnet
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow LoadBalancer traffic to API pods
  - from: []  # Allow from anywhere (LoadBalancer needs this)
    ports:
    - protocol: TCP
      port: 4350
    - protocol: TCP
      port: 4000
    - protocol: TCP
      port: 9090
  # Allow internal pod-to-pod communication
  - from:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 5432  # PostgreSQL
    - protocol: TCP
      port: 6379  # Redis
  egress:
  # Allow all egress (for external API calls to testnet, archive, etc.)
  - {}