export * as system from './system/events'
export * as balances from './balances/events'
export * as currency from './currency/events'
export * as tokens from './tokens/events'
export * as predictionMarkets from './prediction-markets/events'
export * as parachainStaking from './parachain-staking/events'
export * as styx from './styx/events'
