services:
  db:
    image: postgres:14  # CockroachDB cluster might be a better fit for production deployment
    container_name: db
    restart: always

  ingest:
    image: subsquid/substrate-ingest:firesquid
    container_name: ingest
    restart: on-failure
    depends_on:
      - db

  gateway:
    image: subsquid/substrate-gateway:firesquid
    container_name: gateway