version: "3.4"
services:
  db:
    image: postgres:12

  indexer:
    image: subsquid/hydra-indexer:5.0.0-alpha.29
    depends_on:
      - db
      - redis

  indexer-gateway:
    image: subsquid/hydra-indexer-gateway:5
    depends_on:
      - redis
      - db
      - indexer-status-service
      - indexer

  indexer-status-service:
    image: subsquid/hydra-indexer-status-service:5
    depends_on:
      - redis
      
  redis:
    image: redis:6.0-alpine