version: "3.4"
services:
  db:
    volumes:
      - /cockroach/cockroach-data
    command: start-single-node --insecure
    
  ingest:
    volumes:
      - "../typesBundle.json:/config/typesBundle.json"
    command: [
      "--types-bundle", "/config/typesBundle.json",
      "-e", "wss://bsr.zeitgeist.pm",
      "-c", "20", # allow up to 20 pending requests for the above endpoint (default is 5)
      "--out", "postgres://root@db:26257/defaultdb"
    ]

  gateway:
    environment:
      DATABASE_MAX_CONNECTIONS: 5
      RUST_LOG: "actix_web=info,actix_server=info"
    command: [ "--database-url", "postgres://root@db:26257/defaultdb" ]
    ports:
      - 8888:8000