version: "3.4"
services:
  db:
    volumes:
      - /cockroach/cockroach-data
    command: start-single-node --insecure
    
  ingest:
    volumes:
      - "../typesBundle.json:/config/typesBundle.json"
    ports:
      - 9090:9090
    command: [
      "--types-bundle", "/config/typesBundle.json",
      "-e", "${WS_TEST_URL}",
      "-c", "20",
      "-e", "${WS_TEST_URL2}",
      "-c", "20",
      "--out", "postgres://root@db:26257/defaultdb"
    ]

  gateway:
    environment:
      DATABASE_MAX_CONNECTIONS: 5
      RUST_LOG: "actix_web=info,actix_server=info"
    ports:
      - 8888:8000
    command: [ "--database-url", "postgres://root@db:26257/defaultdb" ]