version: "3.4"
services:
  db:
    volumes:
      - /cockroach/cockroach-data
    command: start-single-node --insecure
    
  ingest:
    volumes:
      - "../typesBundle.json:/config/typesBundle.json"
    command: [
      "--types-bundle", "/config/typesBundle.json",
      "-e", "${WS_TEST_URL}",
      "-c", "20",
      "-e", "${WS_TEST_URL2}",
      "-c", "20",
      "--out", "postgres://root@db:26257/defaultdb"
    ]
    ports:
      - 9090:9090

  gateway:
    environment:
      DATABASE_MAX_CONNECTIONS: 5
      RUST_LOG: "actix_web=info,actix_server=info"
    command: [ "--database-url", "postgres://root@db:26257/defaultdb" ]
    ports:
      - 8888:8000
  
  explorer:
    image: subsquid/substrate-explorer:firesquid
    environment:
      DB_TYPE: cockroach
      DB_HOST: db
      DB_PORT: 26257
      DB_NAME: defaultdb
      DB_USER: root
    ports:
      - 4444:3000
    depends_on:
      - db