version: "3.4"
services:
  db:
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: squid-archive

  ingest:
    command: [
      "-e", "ws://node:9944/0",
      "-c", "20", # allow up to 20 pending requests for the above endpoint (default is 5)
      "--out", "postgres://postgres:postgres@db:5432/squid-archive"
    ]
    ports:
      - 9091:9090
    depends_on:
      - node

  gateway:
    environment:
      RUST_LOG: "substrate_gateway=info,actix_server=info"
    command: [
      "--database-url", "postgres://postgres:postgres@db:5432/squid-archive",
      "--database-max-connections", "3", # max number of concurrent database connections
    ]
    ports:
      - 8888:8000

  explorer:
    image: subsquid/substrate-explorer:firesquid
    container_name: explorer
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: "squid-archive"
      DB_USER: "postgres"
      DB_PASS: "postgres"
    ports:
      - 4444:3000
      
  node:
    image: zeitgeistpm/zeitgeist-node:v0.3.5
    container_name: node
    ports:
      - 9944:9944
    command: --dev --ws-external --pruning archive
    environment:
      - PORT=9944
      - NODE_URI=ws://node:9944/0