version: "3.4"
services:
  db:
    volumes:
      - data:/cockroach/cockroach-data
    command: start-single-node --insecure

  ingest:
    depends_on:
      - node
    ports:
      - 9091:9090
    command:
      [
        "-e",
        "ws://node:9944/0",
        "-c",
        "5",
        "--out",
        "postgres://root@db:26257/defaultdb"
      ]

  gateway:
    environment:
      RUST_LOG: "actix_web=info,actix_server=info"
    ports:
      - 8888:8000
    command:
      [
        "--database-url",
        "postgres://root@db:26257/defaultdb",
        "--database-max-connections",
        "10"
      ]

  explorer:
    image: subsquid/substrate-explorer:firesquid
    container_name: explorer
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_TYPE: cockroach
      DB_HOST: db
      DB_PORT: 26257
      DB_NAME: defaultdb
      DB_USER: root
    ports:
      - 4444:3000

  node:
    image: zeitgeistpm/zeitgeist-node:v0.3.6
    container_name: node
    restart: unless-stopped
    environment:
      - PORT=9944
      - NODE_URI=ws://node:9944/0
    ports:
      - 9944:9944
    command: --dev --ws-external --pruning archive

volumes:
  data:
